config_name: "WB06"
prompt_template: "prompt.txt"
banned_elements:
  - "match expressions"
  - "list comprehensions"

required_elements:
  - "Dictionaries"

test_case_hints: 
  - "No test case hints"

additional_requirements:
  - "No additional requirements."

problem_statements:
  - "Implement a structure to support the points in 2D, i.e. with two x and y coordinates. Program then functions for their addition and subtraction"
  - "Program a function that receives a dictionary and a list and generates as output two lists: one with all the values of those elements of the list that are in the dictionary, and another one with those that are NOT in the dictionary."
  - "The QR code (abbreviation of Quick Response Code) was created in 1994 by a Japanese subsidiary of Toyota that manufactures automotive components. These codes allow to store information about a product by encoding it in an NxN square with pixels that can be white or black. In their smallest format, the codes have 21x21 pixels (version 1), and in the largest 177x177 (version 40). Program a application that randomly generates version 1 QR codes and displays them on the screen using, for example, asterisks. Note: use the random library and the randint function to generate the random numbers."

produce-python-docs: false